### ISSUE TITLE
Associate runs with studies

### ISSUE THREAD

**Issue by AleksBekker** [AleksBekker/autospatialqc-api#14]
Nikolaos what information does a study need to have?

**Comment by NKalavros** [comment]
Assay - The name of the instrument or technique used
Tissue - The tissue type used
A unique sample ID - Can just be the auto-incremented one
Study - A name for the set of samples


Possibly, but no for now:

Condition - E.g. healthy, cancer
Tissue site - e.g. Tissue might be intestine and tissue site might be colon

In general, if possible, add details to the README so I can add those as well.
