### ISSUE TITLE
Non production DB

### ISSUE THREAD

**Issue by NKalavros** [AleksBekker/autospatialqc-api#6]
Generate second DB that we'll manually merge with production. Second DB gets POSTed to, and we merge periodically manually to ensure things are well formatted.

**Comment by AleksBekker** [comment]
I believe that having rate-limited API tokens for each user will mostly prevent the issues that a second DB would fix, at least for a relatively small project like this one. As such, I'm going to put this feature on the back burner for now

**Comment by AleksBekker** [comment]
Will solve using #17 for now
